server:
  name: server
  ingress:
    enabled: true
    path: /prometheus
    extraPaths: 
    - path: /*
      backend:
        serviceName: prometheus-server 
        servicePort: 80
  persistentVolume:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 2Gi