statefulset:
  replicas: 1
  updateStrategy:
    type: RollingUpdate
tls:
  enabled: false
auth:
  sasl:
    enabled: false
resources:
  cpu:
    cores: 300m
  memory:
    container:
      max: 1025Mi
    redpanda:
      memory: 1Gi
      reserveMemory: 1Mi
  overprovisioned: true
storage:
  persistentVolume:
    size: 3Gi
external:
  enabled: true
  type: NodePort
  domain: ''
  addresses:
    - localhost
config:
  cluster:
    auto_create_topics_enabled: true
console:
  enabled: false